reload "user.plugins"
reload "user.options"
reload "user.keymaps"
reload "user.lsp"
reload "user.smoothie"
reload "user.harpoon"
reload "user.cybu"
reload "user.neotest"
reload "user.surround"
reload "user.bookmark"
reload "user.todo-comments"
reload "user.jaq"
reload "user.fidget"
reload "user.lab"
reload "user.git"
reload "user.zen-mode"
reload "user.inlay-hints"
reload "user.telescope"
reload "user.bqf"
reload "user.dial"
reload "user.numb"
reload "user.treesitter"
reload "user.neogit"
reload "user.colorizer"
reload "user.lualine"
reload "user.tabnine"
reload "user.copilot"
reload "user.chatgpt"
reload "user.whichkey"
reload "user.neoai"
reload "user.cmp"
reload "user.nvimtree"
reload "nostr"
reload "user.autocommands"
-- reload "user.sqtest"
require "user.sqtest2"
-- reload "user.dbee"
-- lvim.builtin.which_key.mappings["."] = { '<cmd>lua require("user.sqtest2").get_bookmarks()<CR>', "Comment" }
